import React from 'react';
import { BookOpen, Scale, FileSignature, HelpCircle, FileCheck, ShieldAlert } from 'lucide-react';
import { motion } from 'motion/react';

interface TermsProps {
  onBack: () => void;
}

export default function Terms({ onBack }: TermsProps) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -15 }}
      transition={{ duration: 0.4, ease: 'easeOut' }}
      className="p-6 sm:p-10 text-slate-800 space-y-8 relative"
    >
      {/* Sleek Left Arrow Button on Absolute Top Left */}
      <div className="flex items-center justify-between border-b border-slate-100 pb-5">
        <button
          onClick={onBack}
          className="p-2.5 bg-slate-50 hover:bg-slate-100 text-slate-700 hover:text-slate-950 rounded-xl transition-all cursor-pointer border border-slate-200/80 hover:shadow-sm"
          title="Back to Dashboard"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
        </button>
        <div className="flex items-center gap-2">
          <span className="text-[10px] bg-indigo-50 text-indigo-700 font-extrabold px-3 py-1 rounded-full border border-indigo-100 tracking-wider uppercase">
            REGULATORY TERMS v1.0
          </span>
        </div>
      </div>

      <header className="space-y-3">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center text-indigo-600">
            <BookOpen className="w-5.5 h-5.5" />
          </div>
          <h1 className="text-3xl font-black text-slate-900 uppercase tracking-tight">Terms of Use</h1>
        </div>
        <p className="text-slate-500 font-medium text-sm max-w-2xl leading-relaxed">
          Clear rights, absolute user sovereignty over digital properties, and the simple core guidelines of our client-side software.
        </p>
      </header>

      {/* RICH CONTENT (500+ Words) */}
      <div className="space-y-6 text-slate-600 text-sm leading-relaxed max-w-4xl">
        
        <section className="space-y-3">
          <h3 className="text-base font-black text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <Scale className="w-4.5 h-4.5 text-indigo-600" />
            1. Agreement and Functional Acceptance
          </h3>
          <p>
            Welcome to **ImagePixel** ("we", "our", "the App"). By accessing our client-side web compilation workspace, loading conversion tools, pasting alphanumeric payloads, or compiling visual assets, you explicitly acknowledge and agree to be bound by these Terms of Use ("Terms"). If you do not agree to these terms, is completely fine, but you must immediately cease accessing our website interfaces.
          </p>
          <p>
            These Terms constitute a fully binding legal covenant between you and ImagePixel. This software is engineered specifically to empower visual creators, photographic artists, and developers to reclaim absolute control over their imagery. We provide this tool under standard open-access mechanisms, ensuring that everyone can access top-tier bitwise file preservation capabilities without arbitrary restriction.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-base font-black text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <FileSignature className="w-4.5 h-4.5 text-indigo-600" />
            2. Intellectual Property & 100% Data Sovereignty
          </h3>
          <p>
            Unlike modern digital hubs, content networks, or cloud editors that sneaky insert terms claiming "royalty-free sub-licensable rights to modify, distribute, or showcase your uploaded artwork," ImagePixel respects your work. **We do not lay claim to any intellectual property ownership or copyright over the images, graphics, symbols, layout designs, or text files you process.**
          </p>
          <p>
            The original image is yours, and consequently, the compiled alphanumeric string (Base64 matrix representation) generated by our local client sandbox is also 100% yours. You possess absolute, unhindered rights to copy, share, print, archive, sell, monetize, or store your generated codes in any form you choose.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-base font-black text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <FileCheck className="w-4.5 h-4.5 text-indigo-600" />
            3. Acceptable Use Policy & Compliance Covenants
          </h3>
          <p>
            By utilizing the ImagePixel software workspace, you promise and covenant to compile and restore only those visual assets that you have the lawful right to edit, transform, or reproduce. You agree to strictly avoid compiling any visual content, malicious payloads, corrupted file headers, or code structures that infringe upon another individual or corporation's copyright, trademark, or general patent protections.
          </p>
          <p>
            Because we do not monitor, record, store, or inspect your processed images, **you bear exclusive, complete legal responsibility for all content processed inside your viewport session.** You agree to indemnify and hold harmless the developers of ImagePixel from any claims, legal suits, monetary demands, damages, or disputes that arise from your use of the application.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-base font-black text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <ShieldAlert className="w-4.5 h-4.5 text-indigo-600" />
            4. Absolute Disclaimer of Warranties & Liability limits
          </h3>
          <p>
            The ImagePixel application workspace, local canvas conversion tools, Base64 compilation structures, and download utilities are provided entirely on an "As-Is" and "As-Available" basis. We do not provide any explicit or implied warranties, guarantees, or safety assurances of any kind. 
          </p>
          <p>
            We do not warrant that our physical file byte reconstruction routines will perform flawlessly under every legacy web browser, or that the formatting of custom base64 payloads will remain completely compatible with all email networks or word processor documents. Under no circumstances shall the visual developers, structural architects, or owners of ImagePixel be liable for any special, incidental, direct, or consequential damages resulting from lost files, corrupt codes, user interface bugs, or general digital interruptions. Your workspace interaction lies entirely at your own discretion and risk.
          </p>
        </section>

      </div>
    </motion.div>
  );
}
